version: '3.1'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: tasks
    ports:
      - "3306:3306"

  todo-list:
    build:
      context: .
      dockerfile: Dockerfile
    image: todo-list:latest
    container_name: todo-list
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tasks
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password123
    volumes:
      - ./app.jar:/app.jar
    restart: always