spring:
  datasource:
    username: root
    password: password123
    url: jdbc:mysql://localhost:3306/tasks

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

    hibernate:
      ddl-auto: update